// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbgjvuxugzzdxpvdsxrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiZ2p2dXh1Z3p6ZHhwdmRzeHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NjExNjMsImV4cCI6MjA5MDMzNzE2M30.qCy-drC_-YoGb3umYu9CNltU7VmewZAeGwA14zpjOnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});